def GPIndividual1(data):
    predictions = (np.sinh(((((np.sinh(data["team1Seed"]) - data["team2Seed"]) + ((np.tanh(data["team2Wmax"]) + ((data["team1Lstd"] + np.minimum( (data["team1losses"]),  (data["year"])))/2.0))/2.0)) + ((data["team2Seed"] == (1.0/(1.0 + np.exp(- data["team2wins"])))).astype(float)))/2.0)) +
                    ((np.cos(((np.round(data["team2Wmedian"]) <= data["team1LAverage"]).astype(float))) - np.maximum( ((data["team1Seed"] * data["team2Lstd"])),  (np.round(np.tanh(np.maximum( (np.maximum( (data["team2Lstd"]),  (data["team2Wstd"]))),  (data["team1wins"]))))))) / 2.0) +
                    ((np.floor(np.minimum( (((1.732051 == data["team1Lmax"]).astype(float))),  (np.cos(data["team1WAverage"])))) == ((np.round(((((-(data["team2LAverage"])) <= data["team2losses"]).astype(float)) - 2.212120)) <= (data["team2Wmin"] * data["team2losses"])).astype(float))).astype(float)) +
                    np.minimum( ((np.abs(data["team1Wmedian"]) - ((data["team1Seed"] >= np.abs(data["team1Lmedian"])).astype(float)))),  (np.round(np.sinh(np.minimum( ((((data["team2WAverage"] != data["team1Seed"]).astype(float)) + data["team2WAverage"])),  ((-(((data["team1Wmin"] >= 2.718282).astype(float)))))))))) +
                    ((np.minimum( (-1.0),  (data["team2Lmax"])) > (data["team2Wmax"] - np.minimum( (data["team1Lmax"]),  ((data["team2Wmin"] * (data["team2Wmax"] - np.minimum( (data["team2Wmin"]),  (np.tanh(np.sin((data["team1Lmax"] * 2.0))))))))))).astype(float)) +
                    np.minimum( (((data["team2WAverage"] >= np.floor(data["team2Wmin"])).astype(float))),  (np.abs(((data["team1Seed"] >= np.sinh(((0.693147 > np.minimum( (data["team2Wmedian"]),  (((data["team1Seed"] <= ((data["team1Wmedian"] <= np.cos(0.693147)).astype(float))).astype(float))))).astype(float)))).astype(float))))) +
                    np.sin(np.sinh(((((-((((-(0.367879)) <= data["team1Lmax"]).astype(float)))) + ((data["team1Wmin"] >= np.floor(data["team1Seed"])).astype(float)))/2.0) - ((np.sin(data["team2Wstd"]) > (data["team2Wmax"] + np.abs(data["team2"]))).astype(float))))) +
                    (((((np.sin(data["team1Lmax"]) > data["team1Wstd"]).astype(float)) != ((data["team1Lmax"] == data["team2wins"]).astype(float))).astype(float)) * (((-(data["team2Wmin"])) + ((data["team1Lstd"] + np.minimum( (data["team2wins"]),  (np.minimum( (data["team1Lmax"]),  (data["team2Wmin"])))))/2.0))/2.0)) +
                    np.maximum( (np.minimum( (data["team1Wmin"]),  (np.ceil(np.minimum( (np.minimum( (0.138462),  (((data["team1Seed"] >= data["team2Lmedian"]).astype(float))))),  (data["team2losses"])))))),  ((((-(np.maximum( (data["team2"]),  (data["team2Seed"])))) > ((data["team1losses"] < 1.414214).astype(float))).astype(float)))) +
                    np.minimum( (np.maximum( (data["team1Lmin"]),  ((-(((data["team1wins"] >= np.cos(0.720430)).astype(float))))))),  (np.minimum( (np.ceil((data["team1Wmedian"] / 2.0))),  ((-(((data["team1Wmin"] >= (1.197370 + ((data["team1Wstd"] < 0.094340).astype(float)))).astype(float)))))))) +
                    ((((-(np.abs(np.abs(((data["team1"] + (-(0.138462)))/2.0))))) * ((0.367879 >= data["team2wins"]).astype(float))) > ((data["team1Wmedian"] + np.maximum( (data["team1"]),  (((0.367879 != data["team1"]).astype(float)))))/2.0)).astype(float)) +
                    ((3.0 == np.maximum( (np.round(np.maximum( (np.sinh(data["team2Lmin"])),  (data["team2LAverage"])))),  (np.floor(np.maximum( (np.sinh(np.maximum( ((data["team1"] * 2.0)),  (data["team1Wmedian"])))),  (np.sinh((data["team2Wmedian"] * np.sin(data["team2WAverage"]))))))))).astype(float)) +
                    np.minimum( (np.ceil(((data["team2Wmin"] + ((0.094340 >= data["team2"]).astype(float)))/2.0))),  ((np.minimum( ((data["team1Lmax"] * data["team1Wmedian"])),  (((data["team1Wmedian"] < (data["team1Wmax"] - data["team2Lmedian"])).astype(float)))) * np.maximum( (data["team2Seed"]),  (data["team1Wmax"]))))) +
                    ((-(((data["team2Wmin"] >= ((-((data["team2Wstd"] + 0.318310))) * (1.0/(1.0 + np.exp(- (-((1.0/(1.0 + np.exp(- 0.318310)))))))))).astype(float)))) * (((1.0/(1.0 + np.exp(- data["year"]))) * data["team1Lmin"]) * data["team2Lstd"])) +
                    np.floor(np.cos(((data["team1WAverage"] * np.minimum( ((data["team1WAverage"] * data["team2Lmax"])),  (data["team1Lstd"]))) * ((np.sin(np.round(data["team2Lmax"])) + ((data["team1LAverage"] != data["team2WAverage"]).astype(float)))/2.0)))) +
                    np.ceil(((2.675680 <= np.abs(np.maximum( ((data["team2"] + np.maximum( (np.abs(data["team1Seed"])),  (data["team2LAverage"])))),  ((0.318310 + (np.minimum( (data["team1Wmedian"]),  (((data["team2"] != data["team2LAverage"]).astype(float)))) - data["team2Lmin"])))))).astype(float))) +
                    ((np.sinh(np.sin(data["team2Lstd"])) * np.round(np.minimum( (np.sin(np.sinh(np.round(data["team1Wmin"])))),  ((np.minimum( (data["team1Lstd"]),  (np.sin(data["team2Lstd"]))) * np.sin(data["team2Lstd"])))))) / 2.0) +
                    ((((data["team2"] <= ((((data["team1Lmin"] + 5.428570)/2.0) + (np.cos(np.maximum( (data["team1Lmin"]),  (np.maximum( ((1.0/(1.0 + np.exp(- data["team1Wmin"])))),  (data["team2LAverage"]))))) / 2.0))/2.0)).astype(float)) <= ((((data["team2"] + 5.428570)/2.0) <= data["team1Wmedian"]).astype(float))).astype(float)) +
                    np.floor(np.cos((data["team2Lmin"] * np.minimum( ((data["team1wins"] + ((data["year"] + data["team2Wmedian"])/2.0))),  ((np.minimum( (data["year"]),  (data["team1wins"])) + ((((data["year"] > data["team2Wmin"]).astype(float)) + data["team2Wmedian"])/2.0))))))) +
                    np.minimum( ((((np.minimum( (((data["team1Wmedian"] >= data["team1WAverage"]).astype(float))),  (data["team2losses"])) / 2.0) > data["team1Lmax"]).astype(float))),  (((data["team1Wmedian"] >= (1.0/(1.0 + np.exp(- ((data["team1Wmax"] > ((data["team1WAverage"] < (data["team1Wmedian"] - data["team2Lmin"])).astype(float))).astype(float)))))).astype(float)))) +
                    (((0.602941 <= (data["team2Wmin"] - ((((np.cos(data["team1Wmedian"]) * 2.0) * 2.0) >= 1.570796).astype(float)))).astype(float)) * np.sin(np.sinh(np.sinh(data["team2Wstd"])))) +
                    (data["team1losses"] * ((data["team1Wmedian"] >= (np.tanh((((((-(data["team1Lmin"])) > 0.434294).astype(float)) != ((np.minimum( (data["team1wins"]),  (((0.434294 <= data["team2losses"]).astype(float)))) < data["team1Wmedian"]).astype(float))).astype(float))) * 2.0)).astype(float))) +
                    np.maximum( (((np.minimum( (data["team1Lmedian"]),  (((data["team2"] > np.maximum( (data["team2losses"]),  (0.585714))).astype(float)))) >= (data["team1WAverage"] + ((1.414214 > data["team2Lmin"]).astype(float)))).astype(float))),  (((data["team2Wmin"] < (data["team1wins"] - 3.141593)).astype(float)))) +
                    np.round((np.round(((data["team2Lmedian"] * ((data["year"] > ((2.675680 + ((data["team1LAverage"] <= np.maximum( (data["team1WAverage"]),  (0.094340))).astype(float)))/2.0)).astype(float))) * 2.0)) * 2.0)) +
                    ((np.abs(np.sinh(np.abs(data["team2Lstd"]))) <= (data["team1Lmax"] * ((data["team2losses"] <= (-(((((data["team2Lstd"] <= np.minimum( (data["team2wins"]),  (data["team2losses"]))).astype(float)) < np.maximum( (data["team2Wmedian"]),  (data["team1losses"]))).astype(float))))).astype(float)))).astype(float)) +
                    np.minimum( (np.cos(data["team1"])),  (((((((((((data["team1"] / 2.0) / 2.0) * 9.869604) <= 0.058823).astype(float)) <= data["team1Wstd"]).astype(float)) == np.ceil(((data["team1"] / 2.0) * 9.869604))).astype(float)) - 0.094340))) +
                    np.maximum( (np.round(((2.212120 <= (data["team1Wmax"] - ((data["team2Lmin"] + data["team2Lmedian"])/2.0))).astype(float)))),  (((3.0 < (data["team2losses"] + np.maximum( ((-(((data["team2Lmin"] + data["team2LAverage"])/2.0)))),  (data["team1"])))).astype(float)))) +
                    ((data["team2wins"] - np.sin(data["team2Wmin"])) * ((np.maximum( (data["team2wins"]),  (0.840000)) <= np.minimum( (data["team1Lmax"]),  ((np.maximum( (data["team2Wmax"]),  ((data["team2wins"] * np.floor(data["team2Wmax"])))) - 0.058823)))).astype(float))) +
                    ((math.tanh((-(1.630430))) > np.sin(np.maximum( (data["team2Wmin"]),  (np.minimum( (np.minimum( (data["team2Seed"]),  (((data["team1LAverage"] + data["team1Wstd"])/2.0)))),  ((((data["team2Seed"] <= data["team2Wmin"]).astype(float)) - data["team2Lstd"]))))))).astype(float)) +
                    np.floor(np.cos(((1.570796 + (np.minimum( (data["team1LAverage"]),  (((data["team1WAverage"] <= ((((((data["team1Wmin"] + data["team1WAverage"])/2.0) < ((data["team2Seed"] >= data["team1Seed"]).astype(float))).astype(float)) + (data["team2Lmedian"] * 0.636620))/2.0)).astype(float)))) * 2.0))/2.0))) +
                    ((data["team2Wmin"] > ((0.318310 + (((1.0/(1.0 + np.exp(- (((data["team2Seed"] * np.maximum( (data["team2"]),  (data["team1Lmax"]))) <= ((data["team2losses"] < data["team1Lmax"]).astype(float))).astype(float))))) < data["team2Wmin"]).astype(float))) * 2.0)).astype(float)) +
                    np.sinh(np.floor((0.367879 - (((((np.minimum( (data["team1LAverage"]),  (np.floor(data["team2WAverage"]))) == ((2.409090 < -3.0))).astype(float)) + (data["team2wins"] * np.sin(np.minimum( (data["team1Lmax"]),  (data["team2WAverage"])))))/2.0) / 2.0)))) +
                    (((data["team1Wmax"] < (-2.0 + ((data["team1wins"] < ((data["team1Wstd"] - (((data["team1Wstd"] * data["team1Wstd"]) < data["team2Wstd"]).astype(float))) - np.sinh((((data["team2Wmax"] > data["team2Lstd"]).astype(float)) * 2.0)))).astype(float)))).astype(float)) * 2.0) +
                    np.tanh(np.sin(np.round(np.tanh((data["team2Wmax"] * ((np.round(data["team2LAverage"]) == ((((data["team1Wmin"] < data["team1LAverage"]).astype(float)) > ((data["team2Wmin"] >= np.cos(np.minimum( (data["team2Wmax"]),  (data["team2LAverage"])))).astype(float))).astype(float))).astype(float))))))) +
                    np.minimum( (np.cos(data["team1losses"])),  (((1.197370 < (data["team2"] * ((data["team1Lmax"] + np.round(((data["team1Wstd"] - ((((data["team1Lmax"] / 2.0) > data["team2Wmax"]).astype(float)) / 2.0)) / 2.0)))/2.0))).astype(float)))) +
                    np.abs(((((data["team1WAverage"] > data["team2Wstd"]).astype(float)) * 2.0) * (np.tanh(1.732051) * ((((data["team1wins"] <= 1.732051).astype(float)) < ((np.cos(data["team2Lmedian"]) > np.abs(np.sin((data["team2losses"] * 2.0)))).astype(float))).astype(float))))) +
                    np.minimum( (np.cos((data["team1Wmin"] * data["team2WAverage"]))),  (np.minimum( (((-(((np.abs(data["team1WAverage"]) > 1.414214).astype(float)))) / 2.0)),  (np.cos(np.maximum( (data["team1Wmax"]),  ((data["team1wins"] - data["team2Wmedian"])))))))) +
                    np.abs(np.minimum( (np.minimum( (((np.abs(data["team1Lmax"]) > ((1.732051 > (data["team1Wmedian"] + data["team1"])).astype(float))).astype(float))),  (np.cos(np.minimum( (data["team2wins"]),  ((-(np.abs(data["team1Lmax"]))))))))),  (np.cos(data["team1LAverage"])))) +
                    ((((((data["team1WAverage"] >= ((data["team1Lmax"] < np.sin(1.584910)).astype(float))).astype(float)) < data["team1Wstd"]).astype(float)) * ((2.302585 < data["team2Wmedian"]).astype(float))) * 2.0) +
                    (-(((((((np.ceil(np.minimum( (data["team2Wmax"]),  (data["team2Wstd"]))) >= (-(data["team2Lmin"]))).astype(float)) > ((data["team2Seed"] <= np.ceil((data["team1Seed"] / 2.0))).astype(float))).astype(float)) + ((5.200000 <= np.floor(data["team2Wmax"])).astype(float)))/2.0))) +
                    np.minimum( (((data["year"] > data["team1Lmedian"]).astype(float))),  (np.minimum( (((data["team2Wmedian"] < np.cos(data["team1"])).astype(float))),  ((np.maximum( (data["team1Lmin"]),  ((np.round(data["team2Lmedian"]) + np.round(np.round(data["team2Lmedian"]))))) / 2.0))))) +
                    ((np.minimum( (np.minimum( (((data["team1Lmin"] <= np.cos(data["team2Wmin"])).astype(float))),  (data["team2losses"]))),  (data["team1Seed"])) >= ((((data["team1LAverage"] < np.cos(((data["team2Wmin"] < data["team1LAverage"]).astype(float)))).astype(float)) != ((data["team1Lmin"] <= np.cos(2.675680)).astype(float))).astype(float))).astype(float)) +
                    (np.minimum( (np.cos(data["team2Seed"])),  (np.floor(np.cos((data["team1losses"] * ((1.0/(1.0 + np.exp(- (-(((((data["team1"] <= np.cos(data["team2Seed"])).astype(float)) >= np.maximum( (data["team1Wstd"]),  (data["team1Wmedian"]))).astype(float))))))) * 2.0)))))) * 2.0) +
                    (3.141593 * (3.141593 * ((np.tanh(data["team1Wmin"]) >= (((data["team1losses"] < ((3.141593 + ((np.round(data["team2Wmin"]) <= (data["team1losses"] * data["team2Wmax"])).astype(float)))/2.0)).astype(float)) * 2.0)).astype(float)))) +
                    np.tanh((data["team1Lmax"] * (-(((data["team2Wmax"] > (1.197370 - (((((data["team2LAverage"] > 1.197370).astype(float)) / 2.0) == ((((((data["team2Wmax"] != data["team1Wstd"]).astype(float)) > data["team1"]).astype(float)) > data["team1Lmin"]).astype(float))).astype(float)))).astype(float)))))) +
                    ((np.minimum( (data["team1wins"]),  (np.minimum( (data["team1wins"]),  (data["team1Wmax"])))) > np.abs((((((data["team1Wmax"] + data["team1Wmax"])/2.0) * (data["team2Lmedian"] * data["team1LAverage"])) < np.cos(np.minimum( (data["team2Seed"]),  (data["team1Lmedian"])))).astype(float)))).astype(float)) +
                    (-(np.maximum( (((data["team1WAverage"] > (np.abs(data["team1Lmin"]) + 2.212120)).astype(float))),  (np.minimum( ((((1.0/(1.0 + math.exp(- 0.693147))) <= (-(data["team1Lstd"]))).astype(float))),  ((data["team2Lmin"] * 2.212120))))))) +
                    (np.minimum( (0.585714),  (np.maximum( (data["team2Wmax"]),  (np.ceil(data["team1WAverage"]))))) * ((np.cos(data["team2Lmin"]) < ((((2.0 > data["team2wins"]).astype(float)) <= (data["team1Lmin"] * ((data["team2Lmin"] > data["team2wins"]).astype(float)))).astype(float))).astype(float))) +
                    np.floor(np.cos((data["team1WAverage"] * np.maximum( (data["team2Lmax"]),  (np.maximum( (((data["team1Wstd"] + ((data["team1Lstd"] + data["team2Lstd"])/2.0))/2.0)),  (np.sin(((((data["team2Lstd"] <= data["team1Lstd"]).astype(float)) + -2.0)/2.0))))))))) +
                    (((((np.round(data["team2Lmax"]) >= ((((1.584910 <= data["team1wins"]).astype(float)) >= ((((data["team2Lmax"] <= 2.718282).astype(float)) >= data["team1Lstd"]).astype(float))).astype(float))).astype(float)) < np.minimum( (data["team2Lmax"]),  ((1.630430 + data["team1"])))).astype(float)) / 2.0) +
                    np.sin(np.minimum( ((data["team1Wmedian"] * (3.141593 * np.sinh(np.maximum( (data["team1"]),  (data["team2Lstd"])))))),  ((-3.0 * ((((data["team1"] >= data["team1LAverage"]).astype(float)) >= ((data["team1Wstd"] > data["team1WAverage"]).astype(float))).astype(float)))))) +
                    ((0.094340 >= np.abs(np.cos((data["team1Wmax"] - (((((data["team1Lmedian"] >= ((data["team1"] >= (-(np.ceil(data["team2Lmax"])))).astype(float))).astype(float)) != np.ceil(np.ceil(data["team2Wmin"]))).astype(float)) * data["team1Lmedian"]))))).astype(float)) +
                    ((np.abs(data["team1Wmax"]) <= (data["team1Seed"] - np.maximum( (np.abs(data["year"])),  (((((np.abs(data["year"]) > np.maximum( ((data["team1Wmin"] * 2.0)),  (data["team2wins"]))).astype(float)) < np.ceil(np.abs(data["team2Wmin"]))).astype(float)))))).astype(float)) +
                    (((-2.0 < data["team2"]).astype(float)) * np.abs((((data["team2"] < data["team1Seed"]).astype(float)) * (((data["team2losses"] <= (-2.0 / 2.0)).astype(float)) + ((data["team2Lstd"] * ((1.570796 < data["year"]).astype(float))) * 2.0))))) +
                    np.minimum( ((((data["team2Lstd"] * ((data["team1Wmax"] > 1.0).astype(float))) + (-((((np.maximum( (data["team1Lmin"]),  (data["team1Wmedian"])) <= data["team2Lstd"]).astype(float)) / 2.0))))/2.0)),  (((data["team1LAverage"] < ((data["team1LAverage"] >= 0.602941).astype(float))).astype(float)))) +
                    (-(((((data["team1Lmin"] <= 0.840000).astype(float)) <= (-((data["team2Lmedian"] * (data["team2Wmax"] + (data["team2Lmin"] + ((data["team2Wstd"] < (data["team2Lmedian"] * np.sinh(data["team2Lmin"]))).astype(float)))))))).astype(float)))) +
                    ((np.minimum( (data["team2wins"]),  (data["team1Wstd"])) > ((1.197370 >= (np.minimum( ((data["team1Wmin"] * data["team1Wstd"])),  (data["team1Wstd"])) - np.minimum( (np.minimum( (data["team2Lmax"]),  (data["team1Lmin"]))),  (data["team2Wmax"])))).astype(float))).astype(float)) +
                    (np.cos((-(data["team2Wmin"]))) * (((data["team2losses"] > data["team1Lmedian"]).astype(float)) * np.sin((data["team2Lstd"] * np.minimum( (np.sinh(data["team1"])),  ((8.0 - data["team2losses"]))))))) +
                    (((-(data["team1WAverage"])) >= (3.0 * np.maximum( (np.maximum( (data["team1Lmax"]),  (data["team2Lstd"]))),  (((data["team2"] < ((1.0/(1.0 + np.exp(- np.tanh((1.0/(1.0 + np.exp(- ((data["team2Wstd"] > data["team1LAverage"]).astype(float))))))))) * 2.0)).astype(float)))))).astype(float)) +
                    np.sinh(np.sinh(((np.maximum( (data["team2losses"]),  ((data["team2Wstd"] * data["year"]))) > ((3.0 - np.cos(((((data["team2Wstd"] > 2.409090).astype(float)) <= data["team1Wmin"]).astype(float)))) - ((data["team2Wstd"] > 2.409090).astype(float)))).astype(float)))) +
                    np.sinh((-(((((((-(((((data["team1Seed"] < data["team2Lstd"]).astype(float)) < data["team2Wmin"]).astype(float)))) >= np.cos((-(data["team2"])))).astype(float)) >= ((data["team1Seed"] < (2.0 - data["team1losses"])).astype(float))).astype(float)) / 2.0)))) +
                    (np.minimum( (((data["team2WAverage"] > data["team1Wmax"]).astype(float))),  (((-(((data["team1"] - (-(((data["team1wins"] >= ((0.094340 > data["team1Wmax"]).astype(float))).astype(float))))) - ((0.094340 > data["team1Wmax"]).astype(float))))) / 2.0))) / 2.0) +
                    (((data["team1"] >= (1.0/(1.0 + np.exp(- np.tanh(data["team1Wstd"]))))).astype(float)) * np.tanh(((data["team1Lmin"] > ((1.0/(1.0 + np.exp(- np.tanh(data["team1Lmin"])))) * np.minimum( ((((1.0/(1.0 + np.exp(- data["team1"]))) + data["team1Wstd"])/2.0)),  (data["team2"])))).astype(float)))) +
                    (((((data["team2Wmax"] * data["team2Wmin"]) >= ((np.floor(data["team2Wmin"]) == ((data["team1WAverage"] <= data["team1WAverage"]).astype(float))).astype(float))).astype(float)) + (-(np.round(np.sin((1.0/(1.0 + np.exp(- np.abs((data["team1Wmin"] - np.cos(data["team2Wmin"])))))))))))/2.0))

    return Outputs(predictions)


